---
- hosts: all
  tasks:
    - name: deploy code
      copy:
        src: java-example.war
        dest: /var/lib/tomcat9/webapps/java-example.war
    - name: permissions
      file:
        name: permission
        path: /var/lib/tomcat9/webapps
        mode: 0777
        state: present