---
- hosts: all
  tasks:
    - name: permissions
      file:
          path: /var/lib/tomcat9/webapps
          mode: 0777
          recurse: yes
          state: directory
    - name: deploy the code
      copy:
        src: java-example.war
        dest: /var/lib/tomcat9/webapps/java-example.war
